# Credits: https://github.com/dreamsofautonomy/zen-omp
# I have only modified it to my needs

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'blue'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:grey'
    background = 'transparent'
    template = ' <green>{{ .HEAD }}</>{{ if .Working.Changed }} <lightMagenta>○[{{ .Working.String }}]{{ end }}</> {{ if .Staging.Changed }}<lightCyan>◇[{{ .Staging.String }}]</>{{ end }} <lightRed>{{ if gt .Behind 0 }}▼{{ end }}{{ if gt .Ahead 0 }}▲{{ end }} {{ if gt .StashCount 0 }}{{ .StashCount }}{{ end }}</>'
    [blocks.segments.properties]
      branch_icon = ' '
      commit_icon = '@'
      fetch_upstream_icon = true
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}magenta{{end}}",
    ]
    background = 'transparent'
    template = '● '

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}",
  ]
  background = 'transparent'
  template = '● '

[secondary_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = '❯❯ '

# Here
[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    type = 'node'
    style = 'plain'
    template =  "<default>via</>  {{ .Full }}"
    background = 'transparent'
    foreground = 'green'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_package_manager = false
      home_enabled = false

  [[blocks.segments]]
    type = 'python'
    style = 'plain'
    template =  "<default>via</>  {{ .Full }}"
    background = 'transparent'
    foreground = 'yellow'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = true
      fetch_virtual_env = true

  [[blocks.segments]]
    type = 'rust'
    style = 'plain'
    template =  "<default>via</>  {{ .Full }}"
    background = 'transparent'
    foreground = 'lightRed'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = true

  [[blocks.segments]]
    type = 'kotlin'
    style = 'plain'
    template =  "<default>via</>  {{ .Full }}"
    background = 'transparent'
    foreground = 'magenta'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = true

  [[blocks.segments]]
    type = 'lua'
    style = 'plain'
    template =  "<default>via</>  {{ .Full }}"
    background = 'transparent'
    foreground = 'blue'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = true

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = ' 󰔚 {{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000
