[colors]
background = "#101419"  
cursor_bg = "#b6beca"    
cursor_border = "#b6beca"
cursor_fg = "#384148"    
foreground = "#b6beca"  
selection_bg = "#fafdff" 
selection_fg = "#101419"
split = "#384148"        

ansi = [
    "#1c252c",
    "#e05f65",
    "#78dba9",
    "#f1cf8a",
    "#70a5eb",
    "#c68aee",
    "#74bee9",
    "#dee1e6",
]

brights = [
    "#384148",
    "#fc7b81",
    "#94f7c5",
    "#ffeba6",
    "#8cc1ff",
    "#e2a6ff",
    "#90daff",
    "#fafdff",
]

[colors.tab_bar]
background = "#384148"

[colors.tab_bar.active_tab]
bg_color = "#101419"
fg_color = "#b6beca"

[colors.tab_bar.inactive_tab]
bg_color = "#384148"
fg_color = "#b6beca"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#1c252c"
fg_color = "#b6beca"

[colors.tab.inactive_tab_edge]
bg_color = "#1c252c"

[colors.tab_bar.new_tab]
bg_color = "#384148"
fg_color = "#dee1e6"

[colors.tab.new_tab_hover]
bg_color = "#1c252c"
fg_color = "#b6beca"

[metadata]
name = 'dark-decay'
origin_url = 'https://github.com/decaycs'